table _Measures
	lineageTag: 2538f8f8-8391-44d9-92b6-0968cac0397d

	measure 'Sales Revenue' = SUM(Sales[TotalRevenue])
		lineageTag: 681148a2-42d8-47ec-9cc3-072b3b74c1cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Cost' = SUMX(Sales, Sales[QuantitySold] * Sales[CostPrice])
		lineageTag: 85de3949-ad94-4692-bec6-0f06eb62a53a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit' = [Sales Revenue] - [Total Cost]
		lineageTag: c2698ab3-4172-4949-930d-fd40773b0530

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Ticket Price' = AVERAGE(Sales[SalePrice])
		lineageTag: e35eb6d5-bf0d-4540-94c8-340129c82a54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales Transactions' = COUNTROWS(Sales)
		formatString: 0
		lineageTag: 701717a8-4743-46a9-bd21-9a0160bd8d82

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

