table _Measures
	lineageTag: 2538f8f8-8391-44d9-92b6-0968cac0397d

	measure 'Sales Revenue' = SUM(Sales[TotalRevenue])
		lineageTag: 681148a2-42d8-47ec-9cc3-072b3b74c1cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Cost' = SUMX(Sales, Sales[QuantitySold] * Sales[CostPrice])
		lineageTag: 85de3949-ad94-4692-bec6-0f06eb62a53a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit' = [Sales Revenue] - [Total Cost]
		lineageTag: c2698ab3-4172-4949-930d-fd40773b0530

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Ticket Price' = AVERAGE(Sales[SalePrice])
		lineageTag: e35eb6d5-bf0d-4540-94c8-340129c82a54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity of Sales' = COUNTROWS(Sales)
		formatString: 0
		lineageTag: 701717a8-4743-46a9-bd21-9a0160bd8d82

	measure 'YTD Quantity of Sales' = TOTALYTD([Quantity of Sales], 'Calendar'[Date])
		formatString: 0
		lineageTag: 11ac6f6e-afea-4d4e-a241-550a84a524fd

	measure 'YTD Revenue' = TOTALYTD([Sales Revenue], 'Calendar'[Date])
		lineageTag: 7db96421-c137-46b4-ad62-87325a0e009e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Cost' = TOTALYTD([Total Cost], 'Calendar'[Date])
		lineageTag: 9477bd96-c38c-4c06-885c-46f64ab2061c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD GP' = TOTALYTD([Gross Profit], 'Calendar'[Date])
		lineageTag: 900499ee-ab8b-4ea2-9bfd-d0199679c2a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Ticket Price' = TOTALYTD([Average Ticket Price], 'Calendar'[Date])
		lineageTag: 9b891c7e-0e86-4b2a-bf06-cdbf2acef95e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

