table Sales
	lineageTag: ae8cdf50-63d8-4f78-bee5-cdab0d0a0761

	column SaleID
		dataType: int64
		formatString: 0
		lineageTag: 4f41e643-c1b1-4b90-84ea-6426bc954c0f
		summarizeBy: none
		sourceColumn: SaleID

		annotation SummarizationSetBy = Automatic

	column TransactionID
		dataType: int64
		formatString: 0
		lineageTag: f19c1012-bc4f-4a7a-a4ac-16b00cff46f7
		summarizeBy: count
		sourceColumn: TransactionID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 57e857de-660d-4863-b3d3-1a03b0155f55
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: ec9ba737-41b3-4c0d-935c-77b6e10a3a8c
		summarizeBy: none
		sourceColumn: ClientID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 10934477-9b6a-4b5a-aeca-fc16c7e0415a
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column LocationID
		dataType: int64
		formatString: 0
		lineageTag: f73ae206-0ca5-48a9-93b5-3aa039dcd2ca
		summarizeBy: count
		sourceColumn: LocationID

		annotation SummarizationSetBy = Automatic

	column EmployeeID
		dataType: int64
		formatString: 0
		lineageTag: babdc08e-feb6-48fd-88f6-f9c5c11b5400
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column QuantitySold
		dataType: int64
		formatString: 0
		lineageTag: aa2e8215-9427-48f8-95ab-6b2d5e6e7894
		summarizeBy: sum
		sourceColumn: QuantitySold

		annotation SummarizationSetBy = Automatic

	column SalePrice
		dataType: double
		lineageTag: 599e0780-5833-4040-8735-581c1da72f7b
		summarizeBy: sum
		sourceColumn: SalePrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount
		dataType: double
		lineageTag: e60b9d98-9413-4847-b5ae-d9fd644b1057
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PurchaseMedium
		dataType: string
		lineageTag: 653ccadc-ef68-4f11-9945-4f3ee1758786
		summarizeBy: none
		sourceColumn: PurchaseMedium

		annotation SummarizationSetBy = Automatic

	column TotalRevenue
		dataType: double
		lineageTag: d5bcfeb4-6787-461b-9540-1c135960f7d2
		summarizeBy: sum
		sourceColumn: TotalRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountPercent
		dataType: double
		lineageTag: 0a56e439-3468-4ff7-8f3a-6c4faf88e1df
		summarizeBy: sum
		sourceColumn: DiscountPercent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\PauloHenriquePereira\OneDrive - Pride Technologies\Paulo's Stuff\Projects\Summary-Sales-Report\Data\Sales.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SaleID", Int64.Type}, {"TransactionID", Int64.Type}, {"Date", type datetime}, {"ClientID", Int64.Type}, {"ProductID", Int64.Type}, {"LocationID", Int64.Type}, {"EmployeeID", Int64.Type}, {"QuantitySold", Int64.Type}, {"SalePrice", type number}, {"DiscountAmount", type number}, {"PurchaseMedium", type text}, {"TotalRevenue", type number}, {"DiscountPercent", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

